### PR TITLE
LPS-53811

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@zxdgoal 

Can you test my changes?

**Comment by zxdgoal** [comment]
Passed manual testing.

**Comment by hhuijser** [comment]
Hey @zxdgoal 

As I am looking at your two fixes for LPS-53811 and 53812, I realize that for LPS-53811, we shoudl move the methods getMessageIdStringParts and getOffset from MessageListenerImpl to MBUtil and use this logic in MBUtil.getMessageId

You see that similar stuff that I did in my commit is done in those two methods... Can you reopen this pull and work on this?

Hugo Huijser: After that you'll have to redo your other fix as well (https://github.com/hhuijser/liferay-portal/pull/2301)

**Comment by zxdgoal** [comment]
I see.

**Comment by zxdgoal** [comment]
See https://github.com/hhuijser/liferay-portal/pull/2302.

**Pull request closed without merging**
