### PR TITLE
LPS-54414 Don't display the message No comments yet because that will be displayed in a different place

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @zxdgoal

I think that we need to change https://github.com/sergiogonzalez/liferay-portal/commit/0d8cf69078ed82cfd3e527d5ce8d0cb181a2263d because if the user is not logged in and the method SSOUtil.isLoginRedirectRequired(themeDisplay.getCompanyId()) returns true we should indicate the user that he needs to login and we should hide the possibility to the user to add a comment, so he shouldn't see either the editor or reply button.

Can you take of that and resend, please?

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @hhuijser

**Comment by zxdgoal** [comment]
Sorry, I was busy with merging security hotfixes.

I seems that Liferay Mentions Editor bundle doesn't start correctly as I am getting NPE when viewing page comment portlet.

**Comment by izaera** [comment]
@zxdgoal Please see this PR: https://github.com/brianchandotcom/liferay-portal/pull/25243

It should fix that error.

**Comment by zxdgoal** [comment]
The related code is in MentionsEditorConfigContributor.java

```
		LiferayPortletURL autoCompleteUserURL =
			liferayPortletResponse.createResourceURL("1_WAR_mentionsportlet");

		String source =
			autoCompleteUserURL.toString() + "&" +
				PortalUtil.getPortletNamespace("1_WAR_mentionsportlet");
```

The toString causes NPE.

**Comment by zxdgoal** [comment]
@sergiogonzalez, @izaera

The pr @izaera mentioned overpass the code I mentioned, so the bug is still there.

As long as they are executed, the NPE should be thrown.

Just a reminder if you are still working on LPS-52978.

Thanks
John.

**Comment by zxdgoal** [comment]
Sent back https://github.com/sergiogonzalez/liferay-portal/pull/2090.

**Pull request closed without merging**
